### ISSUE TITLE
Windows Compatability

### ISSUE THREAD

**Issue by Clgould99** [TheBattCave/TheBattmobile#6]
Currently the auto_sort_data package only works on Elena's laptop. We theorize that this is because she is on a Mac while the everyone else who is experiencing issues is on Windows. 

Goal: Edit the auto_sort_data package to work on both Windows and Mac

**Comment by pvtr1998** [comment]
Successfully created package that runs on windows. Updated package can be found in auto_sort_data branch. The original package is now labeled auto_sort_data-ORIGINAL.
